# Generated by Django 5.0.4 on 2024-04-08 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                ("bill_id", models.AutoField(primary_key=True, serialize=False)),
                ("bill_date", models.DateField()),
                ("bill_active", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_label", models.CharField(max_length=255)),
                ("product_quantity", models.IntegerField()),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "product_bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="SplitEase.bill"
                    ),
                ),
            ],
        ),
    ]
