# Generated by Django 5.0.4 on 2024-04-08 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SplitEase", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                ("participant_id", models.AutoField(primary_key=True, serialize=False)),
                ("participant_name", models.CharField(max_length=255)),
                (
                    "participant_bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="SplitEase.bill"
                    ),
                ),
            ],
        ),
    ]
