# Generated by Django 5.0.4 on 2024-04-08 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SplitEase", "0002_participant"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipantProductContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contributes", models.BooleanField(default=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SplitEase.participant",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SplitEase.product",
                    ),
                ),
            ],
        ),
    ]
