# Generated by Django 5.0.4 on 2024-04-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SplitEase", "0003_participantproductcontribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_price",
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
