# Generated by Django 5.0.4 on 2024-04-10 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("SplitEase", "0004_product_product_total_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_price",
        ),
    ]
