# Generated by Django 5.0.4 on 2024-04-10 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SplitEase", "0006_product_product_price_per_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantproductcontribution",
            name="bill",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="SplitEase.bill",
            ),
            preserve_default=False,
        ),
    ]
