# Generated by Django 5.0.4 on 2024-04-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SplitEase", "0007_participantproductcontribution_bill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participantproductcontribution",
            name="contributes",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
