# Generated by Django 5.0.4 on 2024-04-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SplitEase", "0008_alter_participantproductcontribution_contributes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_price_per_unit",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=9, null=True
            ),
        ),
    ]
