# Generated by Django 5.0.4 on 2024-04-11 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SplitEase", "0012_alter_product_product_price_per_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="participant_bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="SplitEase.bill",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="SplitEase.bill",
            ),
        ),
    ]
