name: prod

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Execute SSH commmands on remote server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ${{ secrets.USER_PROD }}
          key: ${{ secrets.SSH_KEY_PROD }}
          port: 22
          script: |
            cd /var/www/splitease
            git reset --hard HEAD
            git pull
            sudo systemctl restart splitease.service
